server:
  port: 8081
spring:
  application:
    name: root-service
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'    